### ISSUE TITLE
NSQ 1.0.0 Compatibility

### ISSUE THREAD

**Issue by tanji** [mschneider82/logstash-output-nsq#2]
Could you update your dependencies to nsq-ruby-2.1.0?
Earlier versions do not support NSQ 1.0.0.

Thanks in advance

**Comment by mschneider82** [comment]
Hi

currently its configured with `"nsq-ruby", ">= 2.0.0"`

When you deinstall the plugin and reinstall it, it will get the latest version of nsq-ruby

If this will not work for you i can update the dependency settings, but in my setup it just installed the latest version to: `/usr/share/logstash/vendor/bundle/jruby/1.9/gems/nsq-ruby-2.1.0/lib`

Best regards
Matthias

**Comment by mschneider82** [comment]
just updated and pushed, also a shutdown bug was fixed
